/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shop;

import shop.factories.AbstractFactory;
import shop.factories.EconomicTravel;

public class App {

    public static void main(String[] args) {
        AbstractFactory bookingEcoFactory = new EconomicTravel();
        Client clientEco = new Client(bookingEcoFactory);
        clientEco.generateBooking();

        AbstractFactory bookingPremiumFactory = new EconomicTravel();
        Client clientPremium = new Client(bookingPremiumFactory);
        clientPremium.generateBooking();

    }
}
